{% set version = "0.6.1" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: 6dfa1c57a6c660d9457ca0f563d4ff613c00bfaee5399917cc22a62ebc179b6c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools-scm
  run:
    - python >=3.7
    - dask
    - future
    - numpy
    - xarray >=0.17.0

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
