{% set version = "0.6.0" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: 2d14b3a69a0694edf26dfaee1e9f7310148eb3837880ae2da0f2214c0ffbffed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - dask
    - future
    - numpy
    - xarray >=0.14.1

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
