{% set version = "0.5.2" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: 104724222a193474093acce1232f93dc31caea86eb6e299006dad6a2a06c37e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - dask
    - docrep <=0.2.7
    - future
    - numpy
    - xarray >=0.14.1

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
