{% set version = "0.5.0" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: e169dc2f416d70e43c5a70c0a2f319c8240262e4c3e866bbb818d404248d61b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docrep <=0.2.7
    - future
    - numpy
    - xarray >=0.14.1
    - dask

test:
  imports:
    - xgcm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
    - rabernat
