{% set version = "0.2.0" %}

package:
  name: xgcm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xgcm/xgcm-{{ version }}.tar.gz
  sha256: 0bc42b291808495f5ef225156ad744ef79daaf3d22e337630bb09d51b76a3c33

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - xarray
    - dask
    - numpy
    - future
    - docrep

test:
  imports:
    - xgcm

about:
  home: https://github.com/xgcm/xgcm
  license: MIT
  license_file: LICENSE
  summary: General Circulation Model Postprocessing with xarray

extra:
  recipe-maintainers:
    - ocefpaf
    - jbusecke
