travis:
  secure:
    BINSTAR_TOKEN: YGSHAeSwSULN/vDuotUmfxJ2e2sS+q4gxxmyQgy2yZqUPA1DjB+vOKAPkoAxqA2ryIxbP2ep6vCAkYQ65yNhVTNCWb92Qk/bsTqpzVPmBBkVeijdRZp+QUqccBq2QOKql8S5cCIrD7E/qLcmYB5mJ5B4MSC6hrAfuDL4bvPpvStjvuz7tba/9wFAAWn186pVKXOr8p0VI1SOoaxyiHHTHQTZAIxnKUCTPNyhFycigEOspvbRWLGd42TlGCZX484q366msh4RveM2FuiffB5tfZRflFRIEXhNbkemM/wtwnLFB9zJSh58np1YvRNJqJXsOdaSHDBBvIrwkylVrJhGBMCVla1PySmeMFdq9ClrysrcfRsmY72EuF7lLQd2g5weg72v+HVTNPHKbRLph58TvSXIJF7TwTZK9ehGQpo4Jfix8su7J0Yk8F/qXPh3h/nNQqM8LgnZS2IcWu9PRtJ35RlQE8gmk4wIsYngxtQmmWamZ+g9QMfEmJIKn2Hi4FS8HqTmSICYQz0u2IDZGiFS7hNYB+esPGmWWIVMhL5pJq6an1jU6Wu3DhfeY0yIFdcLlTg2gAzxPobxgzeOYM9Uf7QkJFzG7JHNOIhlZXob+eJKqoJMCr5zdgxg6TYGjMaS0TP9YpLhGU9bfQn66pyPmziCzvSmmG8KJuVHcbeNt90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
