travis:
  secure:
    BINSTAR_TOKEN: oChNkWD3q9RFwb4b4PgW5L7qr4AgcY5z1ij1IuNmyLWOIqDniCwG1P2RXw+7UqoXfqWE2VpStAOwN/7Ea9aqzEtNvnkh/jk2n6lgk1lP9HhwL9l4l/tWGNNeMG1RCLMz+Kpdnwvs7hR/w7r+kVlmIxbgWWrooivMl6JO9awqXKCPhgsAvsN+/qAqiCbl+0c/MjKC9ccGyfg+THXhh3inXPQ5uZrvfGMzuMGjFEMDGNf7Z22jzOlD0wnnkitAyDXQ2tROI82Z1+PJJ/05bmKHs+nFtPBqbjNNxXVQSqakeVX/3mg99hCfwF3TrLZiaqGZgr2dYNjNowC0cmTWfCJd9BdUQiI8l8bEWjUXlyUzrtq3whJ1ZYuGm+Xw1lv8rlrBaCU7KVRG3H5WenKNuJYkIXACbckMcJIIyKhDXQircHE4Qapp5EvqOfjl0UWhijjgyKJnPxc4tO/NgpvuRvSNcJyHllAJIjveq0GdwUoY1TmlPYLra1H+exrc8ddmy7/cdn7GAAQAtRJCXB9LE+YQ61QNK/O2N93zndkCNFd1jN37/IPQfjUsUP0lTSies3PAt3xkkC4Ae0CTQnt5Khm2vcrQLfyImmY8MydpQcQYAFEtIW6Y47gOIMRhjM41HH7Cpmq9R6yaJpl84utBmhz63B7deMaBBOeYJX+/NUPTGdg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
